<div id="titulo" class="tituloModulo ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
    <?php echo $this->titulo; ?>
</div>

<div class="tabla">
    <div class="container">
    <?php
    foreach ($this->datos as $formulario) { ?>
        <div class="row">
            <span class="glyphicon glyphicon-file" aria-hidden="true"></span><a href="<?php echo BASE_URL.'Public'.DS.'Descargas'.DS.'Formularios'.DS.$formulario;?>">
            <?php echo $formulario;?></a>
        </div>
     <?php }    ?>
</div>
</div>