<?php
require_once 'LibQ/Fechas.php';
$fecha = new fecha('30-01-2014');
echo 'ahora =>' . $fecha . '<br>';
echo 'dia now => ' . $fecha->getDia() . '<br>';
echo 'dia de la semana now => ' . $fecha->getDiaSemana() . '<br>';
echo 'mes de año now => ' . $fecha->getMesAnio() . '<br>';
echo 'fecha en formato m-d-a '.$fecha->getFecha(). '<br>';
$hoy = new fecha('30-01-2014');
echo 'mes now => ' . $fecha->getMes() . '<br>';
echo 'año now => ' . $fecha->getAnio() . '<br>';
echo 'posicion dia now => ' . $fecha->getPosicionDia() . '<br>';
echo 'semana del mes => ' . $fecha->getSemanaDelMes() . '<br>';
echo 'semana del año => ' . $fecha->getSemanaDelAnio() . '<br>';
echo 'add => 5 dias --> ' . $fecha->add_date($hoy, 5) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('m', '16-06-1970', $fecha->getFecha())) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('d', '16-06-1970', $fecha->getFecha())) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('h', '16-06-1970', $fecha->getFecha())) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('i', '16-06-1970', $fecha->getFecha())) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('s', '16-06-1970', $fecha->getFecha())) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('m', '19-04-1988', $fecha->getFecha())) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('d', '19-04-1988', $fecha->getFecha())) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('h', '19-04-1988', $fecha->getFecha())) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('i', '19-04-1988', $fecha->getFecha())) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('s', '19-04-1988', $fecha->getFecha())) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('m', '14-09-1994', $fecha->getFecha())) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('d', '14-09-1994', $fecha->getFecha())) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('h', '14-09-1994', $fecha->getFecha())) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('i', '14-09-1994', $fecha->getFecha())) . '<br>';
echo 'edad --> ' . intval($fecha->s_datediff('s', '14-09-1994', $fecha->getFecha())) . '<br>';