<div class="panel panel-primary">
<div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
    <h3 class="panel-title"><?php echo $this->titulo; ?></h3>
</div>

    <div class="panel-body">
<table id="lista_dirTelefonico" class="display" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>Id.</th>
            <th>Apellidos y Nombres</th>
            <th>Contacto</th>
            <th>Observaciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->datos as $paciente) { ?>
            <?php foreach ($paciente->getContactos() as $contacto) { ?>
                <tr>
                    <td class="id">
                        <?php echo $paciente->getId(); ?>
                    </td>
                    <td class="apellidos">
                        <?php echo $paciente->getApellidos() . ', ' . $paciente->getNombres(); ?>
                    </td>
                    <td class="tabla_contacto">
                        <?php echo $contacto; ?>
                    </td>
                    <td class="observaciones">
                        <?php echo $contacto->getObservaciones(); ?>
                    </td>
                </tr>
            <?php } ?>
        <?php } ?>
    </tbody>
</table>
    </div>
    </div>