<div class="panel panel-primary">
<div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
    <h3 class="panel-title"><?php echo $this->titulo; ?></h3>
</div>
    <div class="panel-body">
<table id="lista_pacientes" class="table table-striped table-hover">
    <thead>
        <tr>
            <th>Id</th>
            <th>Apellidos y Nombres</th>
            <th>Domicilio</th>
            <th>Nro.Doc.</th>
            <th>Fecha Nac.</th>
            <th>Diagnóstico</th>
        </tr>
    </thead>
    <tbody>
    <?php 
    foreach ($this->datos as $paciente) { 
        echo '<tr id="' . $paciente->getId() . '">';
            echo '<td>' . $paciente->getId() . '</td>';?>
            <td>
                <?php echo $paciente->getApellidos() . ', ' . $paciente->getNombres(); ?>
            </td>
            <td>
                <?php echo $paciente->getFistDomicilio(); ?>
            </td>
            <td>
                <?php echo $paciente->getNro_doc(); ?>
            </td>
            <td>
                <?php echo $paciente->getFecha_nac() . ' (' . $paciente->getEdad() .')'; ?>
            </td>
            <td>
                <?php echo $paciente->getDiagnostico(); ?>
            </td>
<!--            <td><img src="<?php echo $paciente->getFoto() ?>" class="foto_usuario_128"></td>-->
        </tr>
    <?php } ?>
        </tbody>
</table>
        </div>
</div>