<div>
    <form id="hterapeutica" method="post" action="?option=Paciente&sub=hterapeutica&met=nuevo&id=<?php echo $this->datos->getId(); ?>">
        <input type="hidden" name="guardar" value="1" />
        <input type="hidden" name="idPaciente" value="<?php if ($this->datos->getId()) echo $this->datos->getId(); ?>" id="idPaciente">
        <label for="terapia" class="optional">Terapia:</label> 
        <select name="terapia" id="terapia">
            <optgroup id="terapia-optgroup-0" label="0">
                <option value="7" label="APOYO ESCOLAR">APOYO ESCOLAR</option>
            </optgroup>
            <optgroup id="terapia-optgroup-1" label="1">
                <option value="8" label="ASIST. SOCIAL">ASIST. SOCIAL</option>
            </optgroup>
            <optgroup id="terapia-optgroup-2" label="2">
                <option value="6" label="Ed PSICOMOTRIZ">Ed PSICOMOTRIZ</option>
            </optgroup>
            <optgroup id="terapia-optgroup-3" label="3">
                <option value="5" label="ESTIMULACION AUDITIVA">ESTIMULACION AUDITIVA</option>
            </optgroup>
            <optgroup id="terapia-optgroup-4" label="4">
                <option value="3" label="FONOAUDIOLOGIA">FONOAUDIOLOGIA</option>
            </optgroup>
            <optgroup id="terapia-optgroup-5" label="5">
                <option value="4" label="KINESIOLOGIA">KINESIOLOGIA</option>
            </optgroup>
            <optgroup id="terapia-optgroup-6" label="6">
                <option value="2" label="PSICOLOGIA">PSICOLOGIA</option>
            </optgroup>
            <optgroup id="terapia-optgroup-7" label="7">
                <option value="1" label="PSICOPEDAGOGIA">PSICOPEDAGOGIA</option>
            </optgroup>
            <optgroup id="terapia-optgroup-8" label="8">
                <option value="9" label="ESTIMULACION TEMPRANA">ESTIMULACION TEMPRANA</option>
            </optgroup>        
        </select>
        
        <label for="tipo_informe" class="optional">Tipo:</label> 
        <select name="tipo_informe" id="tipo_informe">
            <optgroup id="tipo_informe-optgroup-0" label="0">
                <option value="7" label="Evaluativo">Evaluativo</option>
            </optgroup>
            <optgroup id="tipo_informe-optgroup-1" label="1">
                <option value="8" label="Evolutivo">Evolutivo</option>
            </optgroup>
        </select>

        <label for="profesional" class="optional">Profesional:</label> 
        <select name="profesional" id="profesional">
            <?php foreach ($this->listaProfesionales as $profesional): ?>
                <option value=<?php echo $profesional->getId(); ?> label="<?php echo $profesional->getApellidos() . ', ' . $profesional->getNombres(); ?>"><?php echo $profesional->getApellidos() . ', ' . $profesional->getNombres(); ?></option>
            <?php endforeach ?>
        </select>    
        <label for="fechaObservacion" class="required">Fecha:</label>
        <input type="text" class="input" name="fechaObservacion" id="fechaObservacion" value=""  class="hasDatepicker">
        <label for="informe" class="optional">Informe:</label>
        <textarea name="informe" class="input mceEditor" id="informe" rows="4" cols="60"></textarea>
        <input type="submit" class="boton" name="boton_guardar" value="Guardar">
    </form>        

</div>