<div id="titulo" class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
    <h4><?php echo $this->titulo; ?></h4>
</div>
<div id = "tabs">
    <ul>
        <li><a href="#tabs-1">Datos Principales</a></li>
    </ul>
    <div id = "tabs-1">
<form id="nueva_tarea" method="post" action="" class="form-horizontal" role="form">
    <input type="hidden" name="guardar" value="1" />
    <input type="hidden" name="depende_de" value="<?php echo $this->datos->getDepende_de(); ?>" />
    <input type="hidden" name="id_creador" value="<?php echo $this->datos->getId_creador(); ?>" />
    <div class="form-group">
    <label for="depende_de" class="required col-sm-2 control-label">Depende de:</label>
    <div class="col-sm-10">
    <select class="form-control" name="depende_de" id="depende_de">
        <option value="0" label="Ninguno">Ninguno</option>
        <?php
        foreach ($this->listaTareas as $tarea) { ?>
            <?php if ($tarea->getId() == $this->datos->getDepende_de()) {
                $seleccionado = ' selected="selected" ';
            } else {
                $seleccionado = '';
            } ?>
            <option value="<?php echo $tarea->getId(); ?>" 
                    label="<?php echo $tarea->getDescripcion(); ?>"
                    <?php echo $seleccionado ?>>
                <?php echo $tarea->getDescripcion(); ?>
            </option>
       <?php } ?>
    </select>
    </div>
    </div>
    <div class="form-group">
    <label for="tipo_tarea" class="required col-sm-2 control-label">Tipo de Tarea:</label>
    <div class="col-sm-10">
    <select class="form-control" name="tipo_tarea" id="tipo_tarea">
        <?php
        foreach ($this->listaTipoTareas as $tipoTarea) {
            if ($this->datos->getTipo_tarea() == $tipoTarea) {
                $seleccionado = ' selected="selected" ';
            } else {
                $seleccionado = '';
            }
            echo "<option value=\"$tipoTarea\" label=\"$tipoTarea\" $seleccionado>$tipoTarea</option>";
       }?>
    </select>
    </div>
    </div>
    <div class="form-group">
    <label for="fechaInicio" class="required col-sm-2 control-label">Fecha Inicio:</label>
    <div class="col-sm-10">
    <?php echo '<input type="date" class="form-control" class="hasDatepicker" name="fechaInicio" id="fechaInicio" value="'.
            $this->datos->getFechaInicio() . '" placeholder="Ingrese fecha inicio">'; ?>
    </div>
    </div>
    <div class="form-group">
    <label for="fechaFin" class="col-sm-2 control-label">Fecha Fin:</label>
    <div class="col-sm-10">
    <?php echo '<input type="date" class="form-control" name="fechaFin" id="fechaFin" value="'.
            $this->datos->getFechaFin() . '" placeholder="Ingrese fecha fin">'; ?>
    </div>
    </div>
    <div class="form-group">
    <label for="descripcion" class="col-sm-2 control-label">Descripción:</label>
    <div class="col-sm-10">
    <input type="text" class="form-control" name="descripcion" id="descripcion" value="<?php if ($this->datos->getDescripcion()) echo $this->datos->getDescripcion(); ?>" placeholder="Ingrese la descripcion" autocomplete="on">
    </div>
    </div>
    <div class="form-group">
        <label for="estado" class="col-sm-2 control-label">Estado:</label>
        <div class="col-sm-10">
    <select class="form-control" name="estado" id="estado">
        <?php
        foreach ($this->listaEstados as $estado) {
            if ($this->datos->getEstado() == $estado) {
                $seleccionado = ' selected="selected" ';
                $seleccionado = '';
            }
            echo "<option value=\"$estado\" label=\"$estado\" $seleccionado>$estado</option>";
       }?>
    </select>
        </div>
    </div>
    <div class="form-group">
    <label for="historial" class="required col-sm-2 control-label">Historial:</label>
    <div class="col-sm-10">
    <textarea class="form-control mceEditor" name="historial" id="historial" rows="6"><?php if ($this->datos->getObservaciones()) echo $this->datos->getObservaciones(); ?></textarea>
    </div>
    </div>
    <div class="form-group">
    <label for="observaciones" class="required col-sm-2 control-label">Observaciones:</label>
    <div class="col-sm-10">
    <textarea class="form-control mceEditor defaultSimpleSkin" name="observaciones" id="observaciones" rows="6"> </textarea>
    </div>
    </div>
    <input type="submit" class="btn btn-lg btn-primary btn-block" name="boton_guardar" value="Guardar">
</form>
</div>
</div>