<div id="titulo" class="tituloModulo ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
    <?php echo $this->titulo; ?>
</div>
<div>
<form id="nueva_tarea" method="post" action="">
    <input type="hidden" name="guardar" value="1" />
    <input type="hidden" name="depende_de" value="<?php echo $this->datos->getDepende_de(); ?>" />
    <input type="hidden" name="id_creador" value="<?php echo $this->datos->getId_creador(); ?>" />

    <label for="depende_de" class="required">Depende de:</label>
    <select class="select" name="depende_de" id="depende_de">
        <option value="0" label="Ninguno">Ninguno</option>
        <?php
        foreach ($this->listaTareas as $tarea) { ?>
            <?php if ($tarea->getId() == $this->datos->getDepende_de()) {
                $seleccionado = ' selected="selected" ';
            } else {
                $seleccionado = '';
            } ?>
            <option value="<?php echo $tarea->getId(); ?>" 
                    label="<?php echo $tarea->getDescripcion(); ?>"
                    <?php echo $seleccionado ?>>
                <?php echo $tarea->getDescripcion(); ?>
            </option>
       <?php } ?>
    </select>

    
    <label for="tipo_tarea" class="required">Tipo de Tarea:</label>
    <select class="select" name="tipo_tarea" id="tipo_tarea">
        <?php
        foreach ($this->listaTipoTareas as $tipoTarea) {
            if ($this->datos->getTipo_tarea() == $tipoTarea) {
                $seleccionado = ' selected="selected" ';
            } else {
                $seleccionado = '';
            }
            echo "<option value=\"$tipoTarea\" label=\"$tipoTarea\" $seleccionado>$tipoTarea</option>";
       }?>
    </select>

    <label for="fechaInicio" class="required">Fecha Inicio:</label>
    <input type="text" class="input" class="hasDatepicker" name="fechaInicio" id="fechaInicio" value="<?php echo $this->datos->getFechaInicio(); ?>" placeholder="Ingrese fecha inicio">
    <label for="fechaFin" class="optional">Fecha Fin:</label>
    <input type="text" class="input" class="hasDatepicker" name="fechaFin" id="fechaFin" value="<?php echo $this->datos->getFechaFin(); ?>" placeholder="Ingrese fecha fin">
    <label for="descripcion" class="optional">Descripción:</label>
    <input type="text" class="input" name="descripcion" id="descripcion" value="<?php if ($this->datos->getDescripcion()) echo $this->datos->getDescripcion(); ?>" placeholder="Ingrese la descripcion" autocomplete="on">
    <label for="estado" class="optional">Estado:</label>    
    <select class="select" name="estado" id="estado">
        <?php
        foreach ($this->listaEstados as $estado) {
            if ($this->datos->getEstado() == $estado) {
                $seleccionado = ' selected="selected" ';
                $seleccionado = '';
            }
            echo "<option value=\"$estado\" label=\"$estado\" $seleccionado>$estado</option>";
       }?>
    </select>
    
    <label for="historial" class="required">Historial:</label>
    <textarea class="input mceEditor" name="historial" id="historial" rows="6"><?php if ($this->datos->getObservaciones()) echo $this->datos->getObservaciones(); ?></textarea>
    <label for="observaciones" class="required">Observaciones:</label>
    <textarea class="input mceEditor defaultSimpleSkin" name="observaciones" id="observaciones" rows="6"> </textarea>

    <input type="submit" class="boton" name="boton_guardar" value="Guardar">
</form>
</div>