<div class="panel panel-primary">
<div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
    <h3 class="panel-title"><?php echo $this->titulo; ?></h3>
</div>
    <div class="panel-body">
<table id="lista_tareas" class="">
    <thead>
        <tr>
        <th>Nº</th>
        <th>Creado por</th>
        <th>Tipo</th>
        <th>Inicia</th>
        <th>Finaliza</th>
        <th>Descripción</th>
        <th>Estado</th>
        <th>Observaciones</th>
    </tr>
    </thead>
    <tbody>
    <?php
    $i=0;
    foreach ($this->datos as $tarea) {
        $caracter = '';
        if ($tarea->getCaracter()=='urgente'){
            $caracter = 'alert alert-danger';
        }else if($tarea->getCaracter()=='proximo'){
            $caracter = 'alert alert-warning';
        }
        echo '<tr id=' . $tarea->getId() . ' class="' . $caracter . '">';
        echo '<td class="celda id">';
        echo $tarea->getId();
        echo '</td>';
        echo '<td ';
        if(MOSTRAR_ICONOS == 1) {
            echo 'id="apellidos"';
        }
        echo ' class="celda creado_por"><b>';
        echo $tarea->getObjCreador()->getNombre();
        echo '</b></td>';
        echo '<td ';
        if(MOSTRAR_ICONOS == 1) {
            echo 'id="tipo_tarea"';
        }
        echo ' class="celda tipo_tarea">';
        echo $tarea->getTipo_tarea();
        echo '</td>';
        echo '<td ';
        if(MOSTRAR_ICONOS == 1) {
            echo 'id=fecha_nac';
        }
        echo ' class="celda fechaInicio">';
        echo $tarea->getFechaInicio();
        echo '</td>';
        echo '<td ';
        if(MOSTRAR_ICONOS == 1) {
            echo 'id="fecha_nac"';
        }
         echo ' class="celda fechaFin">';
        echo $tarea->getFechaFin();
        echo '</td>';
        echo '<td class="celda descripcion">';
        echo $tarea->getDescripcion();
        echo '</td>';
        echo '<td class="celda estado">';
        echo $tarea->getEstado();
        echo '</td>';
        echo '<td class="celda observaciones">';
        echo $tarea->getObservaciones();
        echo '</td>';
        
        $i++;
        echo '</tr>';
    }
    ?>
    </tbody>
</table>
</div>
</div>