<div id="titulo" class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
    <h4><?php echo $this->titulo; ?></h4>
</div>
<div id = "tabs">
    <ul>
        <li><a href="#tabs-1">Datos Principales</a></li>
    </ul>
    <div id = "tabs-1">

<form id="nuevo_paciente" method="post" action="<?php echo BASE_URL; ?>?option=Tareas&sub=index&met=nuevo" class="form-horizontal" role="form">
    <input type="hidden" name="guardar" value="1" />
    <input type="hidden" name="depende_de" value="<?php if (isset($this->datos['depende_de'])) echo $this->datos['depende_de']; ?>" />
    <div class="form-group">
    <label for="repetir" class="col-sm-2 control-label">Se repite:</label>
    <div class="col-sm-10">
    <select class="form-control" name="repetir" id="repetir">
        <?php
        foreach ($this->listaRepetir as $repetir) { ?>
            <option value="<?php echo $repetir; ?>" 
                    label="<?php echo $repetir; ?>">
                <?php echo $repetir; ?>
            </option>
       <?php } ?>
    </select>
    </div>
    </div>
    <div class="form-group">
    <label for="depende_de" class="required col-sm-2 control-label">Depende de:</label>
    <div class="col-sm-10">
    <select class="form-control" name="depende_de" id="depende_de">
        <option value="0" label="NINGUNO">Ninguno</option>
        <?php
        foreach ($this->listaTareas as $tarea) { ?>
            <option value="<?php echo $tarea->getId(); ?>" 
                    label="<?php echo $tarea->getDescripcion(); ?>">
                <?php echo $tarea->getDescripcion(); ?>
            </option>
       <?php } ?>
    </select>
    </div>
    </div>
    <div class="form-group">
    <label for="tipo_tarea" class="required col-sm-2 control-label">Tipo de Tarea:</label>
    <div class="col-sm-10">
    <select class="form-control" name="tipo_tarea" id="tipo_tarea">
        <?php
        foreach ($this->listaTipoTareas as $tipoTarea) {
            if ($this->datos['tipo_tarea'] == $tipoTarea) {
                $seleccionado = ' selected="selected" ';
            } else {
                $seleccionado = '';
            }
            echo "<option value=\"$tipoTarea\" label=\"$tipoTarea\" $seleccionado>$tipoTarea</option>";
       }?>
    </select>
    </div>
    </div>
    <div class="form-group">
    <label for="fechaInicio" class="required col-sm-2 control-label">Fecha Inicio:</label>
    <div class="col-sm-10">
    <?php
    if (isset($this->datos['fechaInicio'])) {
        $fechaInicio = $this->datos['fechaInicio'];
    }else{
        $fechaInicio = '';
    }
    echo '<input type="date" class="form-control" name="fechaInicio"'.
            'id="fechaInicio" value="'. $fechaInicio . '" placeholder="Ingrese fecha inicio">';   ?>
    </div>
    </div>
    <div class="form-group">
    <label for="fechaFin" class="col-sm-2 control-label">Fecha Fin:</label>
    <div class="col-sm-10">
    <?php
    if (isset($this->datos['fechaFin'])) {
        $fechaFin = $this->datos['fechaFin'];
    }else{
        $fechaFin = '';
    }
    echo '<input type="date" class="form-control" name="fechaFin" '.
            'id="fechaFin" value="' . $fechaFin . '" placeholder="Ingrese fecha fin">'; ?>
    </div>
    </div>
    <div class="form-group">
    <label for="descripcion" class="col-sm-2 control-label">Descripción:</label>
    <div class="col-sm-10">
    <input type="text" class="form-control" name="descripcion" id="descripcion" value="<?php if (isset($this->datos['descripcion'])) echo $this->datos['descripcion']; ?>" placeholder="Ingrese la descripcion" autocomplete="on">
    </div>
    </div>
    <div class="form-group">
    <label for="estado" class="col-sm-2 control-label">Estado:</label>    
    <div class="col-sm-10">
    <select class="form-control" name="estado" id="estado">
        <?php
        foreach ($this->listaEstados as $estado) {
            if ($this->datos['estado'] == $estado) {
                $seleccionado = ' selected="selected" ';
            } else {
                $seleccionado = '';
            }
            echo "<option value=\"$estado\" label=\"$estado\" $seleccionado>$estado</option>";
       }?>
    </select>
    </div>
    </div>
<!--    <label for="historial" class="required">Historial:</label>
<textarea class="input mceEditor" name="historial" id="historial" rows="6"></textarea>-->
    <div class="form-group">
    <label for="observaciones" class="required col-sm-2 control-label">Observaciones:</label>
    <div class="col-sm-10">
    <textarea class="form-control mceEditor defaultSimpleSkin" name="observaciones" id="observaciones" rows="6"> </textarea>
    </div>
    </div>
    <input type="submit" class="btn btn-lg btn-primary btn-block" name="boton_guardar" value="Guardar">
</form>
        </div>
</div>