<div id="titulo" class="tituloModulo ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
    <?php echo $this->titulo; ?>
</div>

<div class="tabla">
    <div class="filaTitulos">
        <?php
        echo '<div class="celda id"><b>Nº</b></div>';
        echo '<div class="celda obraSocial"><b>Denominación</b></div>';
        echo '<div class="celda domicilio"><b>Dirección</b></div>';
        echo '<div class="celda estado"><b>Provincia</b></div>';
        echo '<div class="celda nro_doc"><b>Cuit</b></div>';
        ?>
    </div>
</div>
<div class="tabla">
    <?php
    foreach ($this->datos as $obraSocial) {
        echo '<div id=' . $obraSocial['id'] . ' class="filaDatos">
            <a href="' . BASE_URL . '?option=ObrasSociales&sub=index&cont=editar&id=' . $obraSocial['id'] . '">';
        echo '<div class="celda id">';
        echo $this->i;
        echo '</div>';
        echo '<div ';
        if(MOSTRAR_ICONOS == 1) {
            echo 'id="obraSocial"';
        }
        echo ' class="celda obraSocial"><b>';
        echo $obraSocial['denominacion'];
        echo '</b></div>';
        echo '<div ';
        if(MOSTRAR_ICONOS == 1) {
            echo 'id="domicilio"';
        }
        echo ' class="celda domicilio">';
        echo $obraSocial['direccion'];
        echo '</div>';
        
        echo '<div ';
        if(MOSTRAR_ICONOS == 1) {
            echo 'id="provincia"';
        }
        echo ' class="celda provincia">';
        echo $obraSocial['provincia'];
        echo '</div>';
        
        echo '<div ';
        if(MOSTRAR_ICONOS == 1) {
            echo 'id=nro_doc';
        }
        echo ' class="celda nro_doc">';
        echo $obraSocial['cuit'];
        echo '</div>';
        
        $this->i++;
        echo '</a></div>';
    }
    ?>
</div>
<div id="paginacion">
<?php if (isset($this->paginacion)) echo $this->paginacion; ?>
</div>
<?php if (Session::accesoViewEstricto(array('usuario'))): ?>
    <!--Si el nivel es especial muestro el link-->
    <a href="<?php BASE_URL; ?>?option=ObrasSociales&sub=nuevo">Nuevo</a>
<?php endif; ?>
