-- MySQL Script generated by MySQL Workbench
-- 09/18/14 11:51:27
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema gg000334_contasoft
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gg000334_contasoft` DEFAULT CHARACTER SET latin1 ;
USE `gg000334_contasoft` ;

-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_clientes` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `razon_social` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `domicilio` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `condicion_iva` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cuit` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_compras` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `cuenta` INT(11) NULL DEFAULT NULL,
  `proveedor` INT(4) NOT NULL,
  `fecha_comprobante` DATE NOT NULL DEFAULT '0000-00-00',
  `comprobante` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `tipo_comprobante` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `nro_comprobante` INT(12) UNSIGNED ZEROFILL NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_contactos_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_contactos_cliente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_cliente` INT(11) NOT NULL,
  `tipo` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `valor` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `observaciones` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `eliminado` TINYINT(1) NOT NULL,
  `conta_clientes_id` INT(4) NOT NULL,
  UNIQUE INDEX `id` (`id` ASC),
  INDEX `idAlumno` (`id_cliente` ASC),
  PRIMARY KEY (`conta_clientes_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_proveedores2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_proveedores2` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `razon_social` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `condicion_iva` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cuit` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `tel` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `cel` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_contactos_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_contactos_proveedor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT(11) NOT NULL,
  `tipo` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `valor` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `observaciones` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `eliminado` TINYINT(1) NOT NULL,
  `conta_proveedores2_id` INT(4) NOT NULL,
  UNIQUE INDEX `id` (`id` ASC),
  INDEX `idAlumno` (`id_proveedor` ASC),
  PRIMARY KEY (`conta_proveedores2_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_cuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_cuentas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cuenta` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `descripcion` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `grupo_cuenta` INT(11) NOT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_cuentas_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_cuentas_cliente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cuenta` INT(11) NOT NULL,
  `id_cliente` INT(11) NOT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `conta_clientes_id` INT(4) NOT NULL,
  `conta_cuentas_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `conta_cuentas_id`, `conta_clientes_id`),
  INDEX `fk_conta_cuentas_cliente_conta_clientes1_idx` (`conta_clientes_id` ASC),
  INDEX `fk_conta_cuentas_cliente_conta_cuentas1_idx` (`conta_cuentas_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_cuentas_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_cuentas_proveedor` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cuenta` INT(11) NOT NULL,
  `id_proveedor` INT(11) NOT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `conta_proveedores2_id` INT(4) NOT NULL,
  `conta_cuentas_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `conta_proveedores2_id`, `conta_cuentas_id`),
  INDEX `fk_conta_cuentas_proveedor_conta_proveedores21_idx` (`conta_proveedores2_id` ASC),
  INDEX `fk_conta_cuentas_proveedor_conta_cuentas1_idx` (`conta_cuentas_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_domicilios_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_domicilios_cliente` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `id_cliente` INT(11) NOT NULL,
  `tipo_domicilio` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `calle` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT '',
  `casa_nro` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `barrio` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `localidad` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `cp` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `provincia` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `pais` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `conta_clientes_id` INT(4) NOT NULL,
  PRIMARY KEY (`id`, `conta_clientes_id`),
  INDEX `fk_conta_domicilios_cliente_conta_clientes1_idx` (`conta_clientes_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_domicilios_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_domicilios_proveedor` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `id_proveedor` INT(11) NOT NULL,
  `tipo_domicilio` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `calle` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT '',
  `casa_nro` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `barrio` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `localidad` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `cp` VARCHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `provincia` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `pais` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `conta_proveedores2_id` INT(4) NOT NULL,
  PRIMARY KEY (`id`, `conta_proveedores2_id`),
  INDEX `fk_conta_domicilios_proveedor_conta_proveedores21_idx` (`conta_proveedores2_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_grupo_cuentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_grupo_cuentas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `grupo_cuenta` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `descripcion` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `conta_cuentas_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `conta_cuentas_id`),
  INDEX `fk_conta_grupo_cuentas_conta_cuentas1_idx` (`conta_cuentas_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_honorarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_honorarios` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `cuenta` INT(11) NULL DEFAULT NULL,
  `profesional` INT(4) NOT NULL,
  `fecha_comprobante` DATE NOT NULL DEFAULT '0000-00-00',
  `comprobante` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `tipo_comprobante` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `nro_comprobante` INT(12) UNSIGNED ZEROFILL NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `observaciones` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  INDEX `fecha` (`fecha_comprobante` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_impuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_impuestos` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `impuesto` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `caracter` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `tipo_vencimiento` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `observaciones` VARCHAR(110) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `eliminado` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_ingresos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_ingresos` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `cuenta` INT(11) NULL DEFAULT NULL,
  `cliente` INT(4) NOT NULL,
  `fecha_comprobante` DATE NOT NULL DEFAULT '0000-00-00',
  `comprobante` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `tipo_comprobante` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `nro_comprobante` INT(12) UNSIGNED ZEROFILL NOT NULL,
  `condicion_venta` VARCHAR(16) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `fecha_cobro` DATE NOT NULL DEFAULT '0000-00-00',
  `recibo_nro` VARCHAR(14) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT '0',
  `observaciones` TEXT CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_pagoimpuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_pagoimpuestos` (
  `id` INT(5) NOT NULL AUTO_INCREMENT,
  `impuesto` VARCHAR(30) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `fecha_comprobante` DATE NOT NULL DEFAULT '0000-00-00',
  `total` DOUBLE NOT NULL,
  `observaciones` VARCHAR(110) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = MyISAM
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`cronos_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`cronos_personal` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nomina` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `apellidos` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `nombres` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT NULL,
  `tipo_doc` INT(11) NOT NULL,
  `nro_doc` VARCHAR(10) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL DEFAULT '0',
  `cuil` VARCHAR(11) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `domicilio` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NULL DEFAULT '',
  `localidad` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `cargo` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `fecha_nac` DATE NOT NULL DEFAULT '0000-00-00',
  `nacionalidad` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `sexo` VARCHAR(5) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nro_doc` (`nro_doc` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_sueldos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_sueldos` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `idPersonal` INT(11) NOT NULL,
  `periodo_pago` DATE NOT NULL DEFAULT '0000-00-00',
  `nro_recibo` INT(14) UNSIGNED ZEROFILL NULL DEFAULT NULL,
  `remuneracion_gravada` DECIMAL(10,2) NOT NULL,
  `remuneracion_no_gravada` DECIMAL(10,2) NULL DEFAULT '0.00',
  `descuentos` DECIMAL(10,2) NULL DEFAULT '0.00',
  `total` DECIMAL(10,2) NOT NULL,
  `eliminado` TINYINT(1) NOT NULL DEFAULT '0',
  `cronos_personal_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `cronos_personal_id`),
  INDEX `fk_conta_sueldos_cronos_personal1_idx` (`cronos_personal_id` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`conta_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`conta_usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `nombre` VARCHAR(255) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `password` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `categoria` VARCHAR(25) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `bloqueado` TINYINT(4) NOT NULL DEFAULT '0',
  `enviarMail` TINYINT(4) NULL DEFAULT '0',
  `fechaRegistro` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `ultimaVisita` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `activo` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `ultima_ip` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_spanish_ci' NOT NULL,
  `eliminado` TINYINT(1) NOT NULL,
  `codigo` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usertype` (`categoria` ASC))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_spanish_ci;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`cronos_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`cronos_permisos` (
  `id_permiso` INT(11) NOT NULL AUTO_INCREMENT,
  `permiso` VARCHAR(100) NOT NULL,
  `key` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_permiso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`cronos_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`cronos_roles` (
  `id_role` INT(11) NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`cronos_permisos_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`cronos_permisos_role` (
  `role` INT(11) NOT NULL,
  `permiso` INT(11) NOT NULL,
  `valor` TINYINT(4) NOT NULL,
  `cronos_roles_id_role` INT(11) NOT NULL,
  `cronos_permisos_id_permiso` INT(11) NOT NULL,
  UNIQUE INDEX `role` (`role` ASC, `permiso` ASC),
  PRIMARY KEY (`cronos_roles_id_role`, `cronos_permisos_id_permiso`),
  INDEX `fk_cronos_permisos_role_cronos_permisos1_idx` (`cronos_permisos_id_permiso` ASC),
  CONSTRAINT `fk_cronos_permisos_role_cronos_roles1`
    FOREIGN KEY (`cronos_roles_id_role`)
    REFERENCES `gg000334_contasoft`.`cronos_roles` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cronos_permisos_role_cronos_permisos1`
    FOREIGN KEY (`cronos_permisos_id_permiso`)
    REFERENCES `gg000334_contasoft`.`cronos_permisos` (`id_permiso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gg000334_contasoft`.`cronos_permisos_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gg000334_contasoft`.`cronos_permisos_usuario` (
  `usuario` INT(11) NOT NULL,
  `permiso` INT(11) NOT NULL,
  `valor` TINYINT(4) NULL DEFAULT NULL,
  `conta_usuarios_id` INT(11) NOT NULL,
  UNIQUE INDEX `usuario` (`usuario` ASC, `permiso` ASC),
  PRIMARY KEY (`conta_usuarios_id`),
  CONSTRAINT `fk_cronos_permisos_usuario_conta_usuarios1`
    FOREIGN KEY (`conta_usuarios_id`)
    REFERENCES `gg000334_contasoft`.`conta_usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
