<div class="panel panel-primary">
    <div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
        <div class="col-sm-2">
            <?php echo $this->titulo; ?>
        </div>
        <div class="col-sm-3">
            <?php
            echo '<input type="date" class="form-control" name="fecha_turno" id="fechaTurno" value="' .
            $this->fecha . '">';
            ?>
        </div>
    </div>

    <div id = "turnosProfesional">
        <div class="col-sm-3">
            <label for = "profesional" class = "optional"><b>Seleccione un profesional:</b></label>
        </div>
        <div class="col-sm-4">
            <select name = "profesional" id = "profesional" onClick = "cambiar();">
                <?php
                foreach ($this->listaProfesionales as $profesional) {
                    echo '<option value="' . $profesional->getId() . '" ' .
                    'label="' . $profesional->getApellidos() . ', ' . $profesional->getNombres() . '">' .
                    $profesional->getApellidos() . ', ' . $profesional->getNombres() .
                    '</option>';
                }
                ?>
            </select>    
        </div>
    </div>

    <div id="turnosPaciente" class="row">
        <div class="col-sm-3">
            <label for="paciente" class="optional"><b>Seleccione un paciente:</b></label> 
        </div>
        <div class="col-sm-4">
            <select name="paciente" id="paciente">
                <option value=0 label=""></option>
                <?php foreach ($this->listaPacientes as $paciente){
                    echo '<option value="' . $paciente->getId() . '" ' .
                            'label="' . $paciente->getApellidos() . ', ' . $paciente->getNombres() . '">' .
                            $paciente->getApellidos() . ', ' . $paciente->getNombres() . 
                            '</option>';
                } ?>
            </select>    
        </div>
    </div>
    
    <div id = "tabs">
        <ul>
            <li><a href="#tabs-1">AM</a></li>
            <li><a href="#tabs-2">PM</a></li>
        </ul>
        <div id = "tabs-1"><?php include_once 'AM.php'; ?></div>
        <div id = "tabs-2"><?php include_once 'PM.php'; ?></div>
    </div>

</div>