<div class="panel panel-primary">
    <div class="panel-heading ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix">
        <h3 class="panel-title"><?php echo $this->titulo; ?></h3>
    </div>

    <div class="panel-body">
        <table id="lista_personal" class="table table-striped table-hover">
            <thead>
                <tr>
                    <th>Nº</th>
                    <th>Apellidos y Nombres</th>
                    <th>Domicilio</th>
                    <th>Nro.Doc.</th>
                    <th>Fecha Nac.</th>
                </tr>
            </thead>
            <tbody>
                <?php
                foreach ($this->datos as $personal) { 
                    echo '<tr id=' . $personal->getId() . '>';
                    echo '<td>';
                    echo $this->i;
                    echo '</td>';
                    echo '<td>';
                    echo $personal->getApellidos() . ', ' . $personal->getNombres();
                    echo '</td>';
                    echo '<td>';
                    echo $personal->getDomicilio();
                    echo '</td>';
                    echo '<td>';
                    echo $personal->getNro_doc();
                    echo '</td>';
                    echo '<td title="' . $personal->getEdad() . ' años">';
                    echo $personal->getFecha_nac();
                    echo '</td>';
//                    echo '<td personal=' . $personal->getId() . '">';
//                    echo '<img src="' . $personal->getFoto() . '" class="foto_usuario_32">';
//                    echo '</td>';
                    $this->i++;
//                    echo '<span><img src="' . $personal->getFoto() . '" class="foto_usuario_128"></span>';
                    echo '</tr>';
                }
                ?>
            </tbody>
        </table>
